---
- name: Install Memcached
  apt: name=memcached state=latest

- name: 'Php php-memcached'
  apt: name=php-memcached state=latest

- name: Ensure Memcached is running
  service: name=memcached state=started enabled=yes
